name: ext-http-parser

on: [push, pull_request]

jobs:
  build-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: phpize && ./configure
    - name: make && make install
      run: make -j$(sysctl -n hw.ncpu) && sudo make install
    - name: run test
      run: export TEST_PHP_ARGS="-d zend_extension=http_parser.so && cd tests && ./start.sh

  build-ubuntu-old:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: phpize && ./configure
    - name: make && make install
      run: make -j$(sysctl -n hw.ncpu) && sudo make install
    - name: run test
      run: export TEST_PHP_ARGS="-d zend_extension=http_parser.so && cd tests && ./start.sh

  build-macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: phpize && ./configure
    - name: make && make install
      run: make -j$(sysctl -n hw.ncpu) && sudo make install
    - name: run test
      run: export TEST_PHP_ARGS="-d zend_extension=http_parser.so && cd tests && ./start.sh
